version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo `$ECR_URL`
      - echo `$CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7`
      - echo `$CONTAINER_NAME`
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 375588229801.dkr.ecr.ca-central-1.amazonaws.com/flask-app:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 375588229801.dkr.ecr.ca-central-1.amazonaws.com/flask-app:latest
      - printf '[{"name":"reachbc-develop-api","imageUri":"375588229801.dkr.ecr.ca-central-1.amazonaws.com/flask-app:latest"}]' > imadefinitions.json
artifacts:
  files:
    - '**/*'