version: 0.2

phases:
  build:
    commands:
      - docker build -t flask-app .
      - docker tag flask-app:latest 375588229801.dkr.ecr.ca-central-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - docker push 375588229801.dkr.ecr.ca-central-1.amazonaws.com/flask-app:latest